name: docker

on:
  workflow_dispatch:
    inputs: 
      publish:
        type: boolean
        required: true
        description: "Publish to repo"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nictoarch-modelling

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Nictoarch.Modelling.App/Dockerfile
          push: ${{ inputs.publish }}
          tags: nictoarch-modelling:latest
